# -*- coding: utf-8 -*-
"""Gemma_DSPY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtOveNdaGO41VA7HL3r4q3uoO0Ix_NWp

**Direct Script Without Structured Formating**
"""

import dspy
import re

def setup_dspy_with_gemma():
    """Configure DSPy with Gemma 3 27B IT model (no structured output)."""
    gemma_client = dspy.LM(
        model="gemini/gemma-3-27b-it",
        api_key='AIzaSyAuAsuPM3l0zA40tWfonxJdoyEOdrUWbk0',
        max_tokens=1024,
        temperature=0.1,
        use_structured_output=False  # must be off for Gemma
    )

    dspy.settings.configure(lm=gemma_client)
    print("✅ DSPy configured with Gemma 3 27B IT successfully")
    return gemma_client


def extract_pan_details_with_gemma(image_url: str):
    """
    Extract PAN card details using Gemma model (plain text mode).
    """
    setup_dspy_with_gemma()
    lm = dspy.settings.lm

    # Send a simple prompt
    prompt = f"""
    You are a document reader.
    Look at the PAN card image from this URL: {image_url}
    Extract and write clearly:
    Name:
    Father's Name:
    Date of Birth (YYYY-MM-DD):
    PAN Number:
    """

    try:
        raw_output = lm(prompt)
        text = raw_output.completion if hasattr(raw_output, "completion") else str(raw_output)
        print("🧾 Raw model output:\n", text)

        # Clean up text - remove markdown formatting, newlines, and quotes
        text = text.replace('**', '').replace('\\n', ' ').replace('\n', ' ').strip()
        if text.startswith('[') and text.endswith(']'):
            text = text[1:-1]
        text = text.strip('"').strip()

        # Basic regex parsing (improved to handle markdown and extract clean values)
        name = re.search(r"Name[:\- ]+(.+?)(?:\*\*|Father\s*Name|\Z)", text)
        father = re.search(r"Father(?:'s)?\s*Name[:\- ]+(.+?)(?:\*\*|Date\s*of\s*Birth|\Z)", text)
        dob = re.search(r"Date\s*of\s*Birth[:\- ]+(.+?)(?:\*\*|PAN\s*Number|\Z)", text)
        pan = re.search(r"PAN\s*Number[:\- ]+\s*([A-Z]{5}\d{4}[A-Z])", text)

        return {
            "name": name.group(1).strip() if name else None,
            "father_name": father.group(1).strip() if father else None,
            "date_of_birth": dob.group(1).strip() if dob else None,
            "pan_number": pan.group(1).strip() if pan else None,
            "success": True,
        }

    except Exception as e:
        return {"success": False, "error": str(e)}


# ------------------------------
# Example test
# ------------------------------
if __name__ == "__main__":
    print("🔍 Testing PAN extraction with Gemma 3 27B IT")
    test_url = "https://pub-d443ea4d18f941cfb2b887bd9ea021ea.r2.dev/PAN_CARD/4.png"
    result = extract_pan_details_with_gemma(test_url)

    if result["success"]:
        print("✅ Extraction Successful!")
        print(f"Name: {result['name']}")
        print(f"Father's Name: {result['father_name']}")
        print(f"Date of Birth: {result['date_of_birth']}")
        print(f"PAN Number: {result['pan_number']}")
    else:
        print(f"❌ Extraction Failed: {result['error']}")

"""**Script Using JSON Adapter**"""

import dspy
import pydantic


# ---------- Define structured output ----------
class PANCardDetails(pydantic.BaseModel):
    name: str | None = None
    father_name: str | None = None
    date_of_birth: str | None = None
    pan_number: str | None = None


# ---------- Define signature ----------
class ExtractPAN(dspy.Signature):
    """Extract details from a PAN card image."""

    image_url: str = dspy.InputField(desc="URL of the PAN card image")
    details: PANCardDetails = dspy.OutputField(desc="Extracted PAN card details")


# ---------- Setup Gemma + JSON adapter ----------
def setup_dspy_with_gemma_adapter():
    gemma_client = dspy.LM(
        model="gemini/gemma-3-27b-it",
        api_key='AIzaSyAuAsuPM3l0zA40tWfonxJdoyEOdrUWbk0',
        max_tokens=1024,
        temperature=0.1,
        use_structured_output=False  # Disable structured output
    )
    # JSONAdapter without native function calling (to avoid developer instructions)
    json_adapter = dspy.JSONAdapter(use_native_function_calling=False)
    dspy.configure(lm=gemma_client, adapter=json_adapter)
    print("✅ DSPy configured with Gemma + JSONAdapter successfully")


# ---------- Extraction function ----------
def extract_pan_details_with_gemma_adapter(image_url: str):
    setup_dspy_with_gemma_adapter()
    predict = dspy.Predict(ExtractPAN)
    result = predict(image_url=image_url)
    return result.details.dict()


# ---------- Alternative: Custom approach without JSONAdapter ----------
def extract_pan_details_custom(image_url: str):
    """
    Extract PAN details using custom JSON prompting (no adapter, no developer instructions).
    """
    setup_dspy_with_gemma()

    # Force JSON output with explicit instructions
    prompt = f"""Look at the PAN card image from this URL: {image_url}

Extract the following details and respond ONLY with valid JSON in this exact format:
{{"name": "...", "father_name": "...", "date_of_birth": "...", "pan_number": "..."}}

If a field is not visible, use null for that value. Do not include any other text."""

    try:
        lm = dspy.settings.lm
        raw_output = lm(prompt)
        text = raw_output.completion if hasattr(raw_output, "completion") else str(raw_output)
        print("🧾 Raw model output:\n", text)

        # Parse JSON
        import json
        import re

        # Try to extract JSON from the response
        json_match = re.search(r'\{.*\}', text, re.DOTALL)
        if json_match:
            json_str = json_match.group(0)
            details = json.loads(json_str)
            return {**details, "success": True}
        else:
            return {"success": False, "error": "No JSON found in response"}

    except Exception as e:
        return {"success": False, "error": str(e)}


# ---------- Test ----------
if __name__ == "__main__":
    test_url = "https://pub-d443ea4d18f941cfb2b887bd9ea021ea.r2.dev/PAN_CARD/4.png"

    print("=" * 60)
    print("Test 1: Direct LM call (plain text mode)")
    print("=" * 60)
    result1 = extract_pan_details_with_gemma(test_url)
    if result1["success"]:
        print("✅ Success!")
        print(f"Name: {result1.get('name')}")
        print(f"Father's Name: {result1.get('father_name')}")
        print(f"Date of Birth: {result1.get('date_of_birth')}")
        print(f"PAN Number: {result1.get('pan_number')}")
    else:
        print(f"❌ Failed: {result1['error']}")

    print("\n" + "=" * 60)
    print("Test 2: JSONAdapter with reduced formatter")
    print("=" * 60)
    try:
        details = extract_pan_details_with_gemma_adapter(test_url)
        print("✅ Success!")
        for k, v in details.items():
            print(f"{k}: {v}")
    except Exception as e:
        print(f"❌ Failed: {e}")

    print("\n" + "=" * 60)
    print("Test 3: Custom JSON prompting")
    print("=" * 60)
    result3 = extract_pan_details_custom(test_url)
    if result3["success"]:
        print("✅ Success!")
        print(f"Name: {result3.get('name')}")
        print(f"Father's Name: {result3.get('father_name')}")
        print(f"Date of Birth: {result3.get('date_of_birth')}")
        print(f"PAN Number: {result3.get('pan_number')}")
    else:
        print(f"❌ Failed: {result3['error']}")